close all 
figure('Resize','off','Units','centimeters','Position',[0 0 18.1 14],'PaperSize',[18.1 14],'PaperPosition',[0 0 18.1 14]);

% plot 2a 
load('./data/fig2a.mat')
load('./data/fig2a_stats.mat')
plot_2a(fig2a,fig2a_stats)

% plot 2b 
load('./data/fig2b.mat')
plot_2b(fig2b)

% plot 2c 
[ fig2c ] = create_fig2c_data(fig2a,fig2b); %   create data of c from data of a+b
[ fig2c_stats ] = create_fig2c_stats(fig2c); %  create statistics
plot_2c(fig2c,fig2c_stats)

% add subplot labels
AxesH = axes('Parent', gcf, ...
  'Units', 'normalized', ...
  'Position', [0, 0, 1, 1], ...
  'Visible', 'off', ...
  'XLim', [0, 1], ...
  'YLim', [0, 1], ...
  'NextPlot', 'add');
text(0.035,0.985, 'a', ...
  'HorizontalAlignment', 'center', ...
  'VerticalAlignment', 'top','fontweight','bold','fontsize',16,'fontname','SansSerif')
text(0.54,0.985, 'b', ...
'HorizontalAlignment', 'center', ...
'VerticalAlignment', 'top','fontweight','bold','fontsize',16,'fontname','SansSerif')
text(0.035,0.392, 'c', ...
'HorizontalAlignment', 'center', ...
'VerticalAlignment', 'top','fontweight','bold','fontsize',16,'fontname','SansSerif')
% %%
% cd('C:\echo_paper_data\nat_neuro_print_figures')
% print('figure2_natcomm_print.png','-dpng','-r300')
% print('figure2_natcomm_print.pdf','-dpdf','-r300')